apiVersion: apps/v1
kind: Deployment
metadata:
  name: keydb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keydb
  template:
    metadata:
      labels:
        app: keydb
    spec:
      containers:
      - name: keydb
        image: eqalpha/keydb
        ports:
        - containerPort: 6379
